### ISSUE TITLE
[🚀4장 User-based 엔드포인트🚀] user-based 엔드포인트에서 에러가 발견되어 문의드립니다.

### ISSUE THREAD

**Issue by paragonyun** [dq-hustlecoding/dqflex-api-example#1]
안녕하세요! 선생님의 책으로 Model Deploy를 공부하고 있습니다. 해당 교재로 스터디를 진행하고 있는데, 팀원 모두 같은 이슈를 마주하고 긴 시간을 함께 고민했으나 문제가 해결 되지 않아 선생님의 깃헙까지 방문하게 되었습니다.

# 📃 이슈 내용
- user-based엔드포인트에서 parameter로 1000이 넘어가는 id를 줬을 때 coo_matrix를 생성하지 못한다.

# 👀 상세 내용
- localhost:8000/user-based/?**params=2135:4.5&params=1231:5** 과 같이 4자리 수의 movieId를 파라미터로 줬을 때 아래와 같은 에러가 발생했습니다.
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\fastapi\applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\JeongSeongYun\Desktop\나의 노력들\Deploying\fullstack-api\app\.\main.py", line 52, in user_based
    result = user_based_recommendation(input_ratings_dict)
  File "C:\Users\JeongSeongYun\Desktop\나의 노력들\Deploying\fullstack-api\app\.\recommender.py", line 122, in user_based_recommendation
    input_matrix = build_matrix_input(input_ratings, items)
  File "C:\Users\JeongSeongYun\Desktop\나의 노력들\Deploying\fullstack-api\app\.\recommender.py", line 112, in build_matrix_input
    return coo_matrix((data, (rows, mapped_idx)), shape=shape).tocsr()
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\scipy\sparse\_coo.py", line 196, in __init__
    self._check()
  File "C:\Users\JeongSeongYun\anaconda3\envs\venv\lib\site-packages\scipy\sparse\_coo.py", line 285, in _check
    raise ValueError('column index exceeds matrix dimensions')
**ValueError: column index exceeds matrix dimensions**
```
- 이에 해당 부분의 코드를 쭉 살펴보니 낮은 번호의 MovieId를 파라미터로 전달 했을 땐 무리 없이 추천 결과를 잘 받을 수 있으나 위의 예시와 같이 높은 번호의 MovieId에 평점을 메기고 조회했을 땐 위와 같은 에러가 발생하는 현상을 발견했습니다.
- 해당 에러는 지정해준 shape보다 더 큰 index를 지정해주었을 때 발생하는 에러였습니다. 
```python
shape = (1, model.item_factors.shape[0])

    return coo_matrix((data, (rows, mapped_idx)), shape=shape).tocsr()
```
- 즉, mapped_idx가 지정한 shape보다 더 클 때 발생하는 것입니다. 
- 그리고 지정해준 shape은 model.item_factors에 기반하는데, 이는 이전에 모델의 학습 재료가 되었던 ratings.csv의 user_id가 610까지인 것에 기인한다는 것 또한 알게되었습니다.
- 혹시 몰라 coo_matrix를 생성할 때 shape을 (1,5000)과 같이 넉넉하게 만들면 coo_matrix가 생성되기는 합니다만, 아래와 같은 새로운 에러가 발생합니다. 
![image](https://user-images.githubusercontent.com/83996346/210361056-028167b2-916b-4c87-a688-05e41551c6cb.png)
- 해당 에러도 결국 610을 벗어난 idx를 받아서 발생한 에러로, 사실 여기서 문제 해결 방안이 떠오르지 않아 이슈에 남기게 되었습니다.

좋은 책으로 재밌게 공부하고 있습니다. 감사드립니다.

**Comment by dq-hustlecoding** [comment]
안녕하세요? 
혹시 모델을 새로 학습시키신 걸까요? 
모델을 기존 모델을 사용하신다면 610 까지만 쓸 수 있는게 맞을 것 같습니다. (제가 정확한 인덱스를 확인하진 못해서 질문에 나온 숫자를 쓴 점 양해바랍니다) 4자리 이상 숫자를 인덱스로 쓰고 싶으신 이유도 궁금합니다 :) 감사합니다!

**Comment by paragonyun** [comment]
> 
아하, 학습된 모델이 user_id가 610까지 있는 데이터셋을 사용해서 그렇군요..! 

- 교재에 따라 최초 학습을 시킨 모델입니다! 

- 4자리 이상 숫자를 인덱스로 사용한 이유는 교재에서 사용된 예시가 2571, 6365가 사용되었기 때문입니다! (102p)

감사합니다 :)

**Comment by akwls** [comment]
안녕하세요, 저도 해당 교재 학습 중 동일한 문제를 마주하였습니다.
글을 남겨주신지 오랜 시간이 지났지만 혹시나 하여 제가 해결한 방법을 공유드립니다.

데이터 학습 시, coo_matrix 는 movieId 를 행, userId 를 열 로 데이터를 학습하였습니다.
```
rating_matrix = coo_matrix(
        (
            ratings_df['rating'].astype(np.float32),
            (
                ratings_df['movieId'].cat.codes.copy(),
                ratings_df['userId'].cat.codes.copy(),
            ),
        ),
    )
```

하지만, user-based 엔드포인트에서 query param으로부터 matrix 입력값을 생성할 때는 userId (rows, 0 으로 고정된 리스트) 를 행, movieId(mapped_idx) 를 열로 생성하였기 때문에 발생하는 문제인 것 같습니다.

```
return coo_matrix((data, (rows, mapped_idx)), shape=shape).tocsr()
```

제가 이 문제를 해결한 방법은, 데이터 학습 시에 userId 를 행, movieId 를 열 로 하여 희소 행렬을 생성하도록 하는 것입니다.
```
rating_matrix = coo_matrix(
        (
            ratings_df['rating'].astype(np.float32),
            (
                ratings_df['userId'].cat.codes.copy(),
                ratings_df['movieId'].cat.codes.copy(),
            ),
        ),
    )
```

이렇게 데이터를 학습시키고, item-based, user-based 엔드포인트 모두 정상 작동하는 것을 확인하였습니다.
(수정 전에는 교재와 출력 결과가 달랐지만, 수정 후에는 출력 결과가 교재와 동일하였습니다.)

거의 2년 전 이슈라 이미 해결하셨을테지만 동일한 문제를 겪을지도 모르는 미래 독자분들을 위해 코멘트 남깁니다 ㅎㅎ
